const fs = require('fs');
const s = [];
function L(x) { s.push(x); }
L('model VehicleType {');
L('  id String @id @default(cuid())'); L('  name String'); L('  slug String @unique');
L('  description String?'); L('  seats Int'); L('  luggage Int'); L('  icon String?');
L('  isActive Boolean @default(true)'); L('  vehicles Vehicle[]'); L('}'); L('');
L('model Vehicle {');
L('  id String @id @default(cuid())'); L('  serviceId String'); L('  vehicleTypeId String');
L('  name String'); L('  slug String'); L('  description String? @db.Text');
L('  seats Int'); L('  luggage Int'); L('  pricePerTrip Decimal @db.Decimal(12, 2)');
L('  pricePerHour Decimal? @db.Decimal(12, 2)'); L('  currency String @default("VND")');
L('  isActive Boolean @default(true)'); L('  metadata Json?');
L('  createdAt DateTime @default(now())'); L('  updatedAt DateTime @updatedAt');
L('  service Service @relation(fields: [serviceId], references: [id])');
L('  vehicleType VehicleType @relation(fields: [vehicleTypeId], references: [id])');
L('  images VehicleImage[]'); L('  bookingItems BookingItem[]'); L('  quotes Quote[]');
L('  @@index([serviceId])'); L('  @@index([vehicleTypeId])'); L('}'); L('');
L('model VehicleImage {');
L('  id String @id @default(cuid())'); L('  vehicleId String'); L('  url String');
L('  alt String?'); L('  isPrimary Boolean @default(false)'); L('  sortOrder Int @default(0)');
L('  vehicle Vehicle @relation(fields: [vehicleId], references: [id], onDelete: Cascade)'); L('}'); L('');
L('model Location {');
L('  id String @id @default(cuid())'); L('  name String'); L('  slug String @unique');
L('  type LocationType'); L('  address String?'); L('  latitude Decimal? @db.Decimal(10, 8)');
L('  longitude Decimal? @db.Decimal(11, 8)'); L('  area String?');
L('  isActive Boolean @default(true)'); L('  metadata Json?');
L('  createdAt DateTime @default(now())'); L('  updatedAt DateTime @updatedAt');
L('  services Service[]'); L('  pickupBookings Booking[] @relation("PickupLocation")');
L('  dropoffBookings Booking[] @relation("DropoffLocation")');
L('  @@index([slug])'); L('  @@index([type])'); L('  @@index([isActive])'); L('}'); L('');
L('enum LocationType { AIRPORT HOTEL RESORT CITY ATTRACTION PICKUP_POINT DROPOFF_POINT }'); L('');
L('model Tour {');
L('  id String @id @default(cuid())'); L('  serviceId String @unique');
L('  duration String?'); L('  meetingPoint String?'); L('  schedule Json?');
L('  capacity Int?'); L('  included Json?'); L('  excluded Json?');
L('  service Service @relation(fields: [serviceId], references: [id])'); L('}'); L('');
L('model Ticket {');
L('  id String @id @default(cuid())'); L('  serviceId String @unique');
L('  validFrom DateTime?'); L('  validUntil DateTime?'); L('  entryInfo String? @db.Text'); L('  availability Json?');
L('  service Service @relation(fields: [serviceId], references: [id])'); L('}'); L('');
L('model Hotel {');
L('  id String @id @default(cuid())'); L('  serviceId String @unique');
L('  stars Int?'); L('  amenities Json?'); L('  checkIn String?'); L('  checkOut String?');
L('  service Service @relation(fields: [serviceId], references: [id])'); L('  rooms HotelRoom[]'); L('}'); L('');
L('model HotelRoom {');
L('  id String @id @default(cuid())'); L('  hotelId String'); L('  name String');
L('  description String? @db.Text'); L('  price Decimal @db.Decimal(12, 2)');
L('  currency String @default("VND")'); L('  capacity Int'); L('  amenities Json?');
L('  isActive Boolean @default(true)'); L('  hotel Hotel @relation(fields: [hotelId], references: [id])'); L('}'); L('');
L('model Restaurant {');
L('  id String @id @default(cuid())'); L('  serviceId String @unique');
L('  openingHours Json?'); L('  menu Json?'); L('  contact Json?'); L('  reservation Boolean @default(false)');
L('  service Service @relation(fields: [serviceId], references: [id])'); L('}'); L('');
L('model Spa {');
L('  id String @id @default(cuid())'); L('  serviceId String @unique');
L('  services Json?'); L('  schedule Json?');
L('  service Service @relation(fields: [serviceId], references: [id])'); L('}'); L('');
L('model Product {');
L('  id String @id @default(cuid())'); L('  serviceId String @unique');
L('  price Decimal @db.Decimal(12, 2)'); L('  currency String @default("VND")');
L('  availability Boolean @default(true)'); L('  details Json?');
L('  service Service @relation(fields: [serviceId], references: [id])'); L('}'); L('');
fs.appendFileSync('prisma/schema.prisma', s.join('\n'), 'utf-8');
console.log('Part 3:', s.length, 'lines appended');
