const fs = require('fs');
const s = [];
function L(x) { s.push(x); }
L('model ServiceCategory {');
L('  id String @id @default(cuid())'); L('  name String'); L('  slug String @unique');
L('  description String? @db.Text'); L('  icon String?'); L('  image String?');
L('  isActive Boolean @default(true)'); L('  sortOrder Int @default(0)');
L('  createdAt DateTime @default(now())'); L('  updatedAt DateTime @updatedAt');
L('  services Service[]'); L('  guides Guide[]');
L('  @@index([slug])'); L('  @@index([isActive])'); L('}'); L('');
L('model Service {');
L('  id String @id @default(cuid())'); L('  name String'); L('  slug String @unique');
L('  shortDescription String?'); L('  description String? @db.Text');
L('  categoryId String'); L('  locationId String?');
L('  basePrice Decimal @db.Decimal(12, 2)'); L('  currency String @default("VND")');
L('  rating Float @default(0)'); L('  reviewCount Int @default(0)');
L('  isActive Boolean @default(true)'); L('  isFeatured Boolean @default(false)');
L('  sortOrder Int @default(0)'); L('  metadata Json?'); L('  policies Json?'); L('  cancellationPolicy Json?');
L('  createdAt DateTime @default(now())'); L('  updatedAt DateTime @updatedAt');
L('  category ServiceCategory @relation(fields: [categoryId], references: [id])');
L('  location Location? @relation(fields: [locationId], references: [id])');
L('  images ServiceImage[]'); L('  prices ServicePrice[]'); L('  availability ServiceAvailability[]');
L('  vehicles Vehicle[]'); L('  bookingItems BookingItem[]'); L('  reviews Review[]');
L('  @@index([slug])'); L('  @@index([categoryId])'); L('  @@index([locationId])');
L('  @@index([isActive, isFeatured])'); L('  @@index([rating])'); L('}'); L('');
L('model ServiceImage {');
L('  id String @id @default(cuid())'); L('  serviceId String'); L('  url String');
L('  alt String?'); L('  isPrimary Boolean @default(false)'); L('  sortOrder Int @default(0)');
L('  service Service @relation(fields: [serviceId], references: [id], onDelete: Cascade)');
L('  @@index([serviceId])'); L('}'); L('');
L('model ServicePrice {');
L('  id String @id @default(cuid())'); L('  serviceId String'); L('  name String');
L('  priceType PriceType @default(STANDARD)'); L('  basePrice Decimal @db.Decimal(12, 2)');
L('  currency String @default("VND")'); L('  minQuantity Int @default(1)'); L('  maxQuantity Int?'); L('  dayOfWeek Int?');
L('  validFrom DateTime?'); L('  validUntil DateTime?'); L('  isActive Boolean @default(true)'); L('  metadata Json?');
L('  createdAt DateTime @default(now())'); L('  updatedAt DateTime @updatedAt');
L('  service Service @relation(fields: [serviceId], references: [id], onDelete: Cascade)');
L('  @@index([serviceId, isActive])'); L('}'); L('');
L('enum PriceType { STANDARD PEAK_SEASON WEEKEND HOLIDAY GROUP PROMOTIONAL }'); L('');
L('model ServiceAvailability {');
L('  id String @id @default(cuid())'); L('  serviceId String'); L('  dayOfWeek Int?');
L('  startTime String?'); L('  endTime String?'); L('  maxCapacity Int');
L('  bookedCount Int @default(0)'); L('  isActive Boolean @default(true)'); L('  specificDate DateTime?');
L('  createdAt DateTime @default(now())'); L('  updatedAt DateTime @updatedAt');
L('  service Service @relation(fields: [serviceId], references: [id], onDelete: Cascade)');
L('  @@index([serviceId, isActive])'); L('  @@index([specificDate])'); L('}'); L('');
fs.appendFileSync('prisma/schema.prisma', s.join('\n'), 'utf-8');
console.log('Part 2:', s.length, 'lines appended');
