const fs = require('fs');
const s = [];
function L(x) { s.push(x); }
L('generator client {'); L('  provider = "prisma-client-js"'); L('}'); L('');
L('datasource db {'); L('  provider = "postgresql"'); L('  url      = env("DATABASE_URL")'); L('}'); L('');
L('model User {');
L('  id            String    @id @default(cuid())'); L('  email         String    @unique');
L('  name          String?'); L('  phone         String?'); L('  passwordHash  String?');
L('  emailVerified DateTime?'); L('  image         String?');
L('  role          UserRole  @default(CUSTOMER)'); L('  isActive      Boolean   @default(true)');
L('  createdAt     DateTime  @default(now())'); L('  updatedAt     DateTime  @updatedAt');
L('  bookings      Booking[]'); L('  reviews       Review[]');
L('  accounts      Account[]'); L('  sessions      Session[]');
L('  notifications Notification[]'); L('  auditLogs     AuditLog[]   @relation("AuditActor")');
L('  @@index([email])'); L('  @@index([role])'); L('}'); L('');
L('model Account {');
L('  id String @id @default(cuid())'); L('  userId String'); L('  type String');
L('  provider String'); L('  providerAccountId String');
L('  refresh_token String? @db.Text'); L('  access_token String? @db.Text');
L('  expires_at Int?'); L('  token_type String?'); L('  scope String?');
L('  id_token String? @db.Text'); L('  session_state String?');
L('  user User @relation(fields: [userId], references: [id], onDelete: Cascade)');
L('  @@unique([provider, providerAccountId])'); L('}'); L('');
L('model Session {');
L('  id String @id @default(cuid())'); L('  sessionToken String @unique');
L('  userId String'); L('  expires DateTime');
L('  user User @relation(fields: [userId], references: [id], onDelete: Cascade)');
L('}'); L('');
L('model VerificationToken {');
L('  identifier String'); L('  token String @unique'); L('  expires DateTime');
L('  @@unique([identifier, token])'); L('}'); L('');
L('enum UserRole { CUSTOMER STAFF MANAGER ADMIN SUPER_ADMIN }'); L('');
fs.writeFileSync('prisma/schema.prisma', s.join('\n'), 'utf-8');
console.log('Part 1:', s.length, 'lines');
